### ISSUE TITLE
Support for the British Library?

### ISSUE THREAD

**Issue by jbcpollak** [lovasoa/dezoomify#1]
Can you add support for the British Library? It seems to use Seadragon, but doesn't work with dezoomify.

Here is an example URL:

http://www.bl.uk/manuscripts/Viewer.aspx?ref=cotton_ms_claudius_b_iv_f012v

**Comment by lovasoa** [comment]
Indeed, they use seadragon. You can use dezoomify by giving it the url of the XML file that describes the image. In your case : http://www.bl.uk/manuscripts/Proxy.ashx?view=cotton_ms_claudius_b_iv_f012v.xml

Dezoomify fails to find this url automatically because it's not present in the raw html source of the page (it's generated by a script).

I could add a special case in the code for the british library, but it's not very clean... The only solution to be sur to be able to dezoomify an image would be to create a browser plugin. But it's too much work for me right now.

**Comment by jbcpollak** [comment]
Thanks for the link, I didn't know what to look for. I suppose you could have different modules to support different websites and a drop down to select the right module. Or maybe just a FAQ for how to look up the right URL for seadragon?

**Comment by lovasoa** [comment]
To find out what the "correct" url is when dezoomify doesn't manage to do it on its own, just open the network traffic panel of your browser (ctrl-maj-Q in firefox), and find which files are requested through xhr.

**Comment by jbcpollak** [comment]
Thanks!

**Comment by Horemheb** [comment]
Dezoomify now works with the British Library,too.  The only BIG problem is that the Library must have some automated system that blocks your ip for an amount of time and u can just download some pages every time... it is very long this way. :(

**Comment by lovasoa** [comment]
If they really block your IP, then there is not much I can do... 

You should [contact them](http://www.bl.uk/aboutus/contact/index.html), or [send them a suggestion](https://forms.bl.uk/aboutus/index.aspx).

If your case of use is legitimate, then they may help you.

**Comment by Horemheb** [comment]
Hm I think if they wanted u to be able to download their books they'd have the download pdf option :) It's a pity I'll have to get back to my older way of saving screen areas and combine them together by Photoshop. :-|

**Comment by Horemheb** [comment]
Another question... I tried to find the right link to submit to seadragon through the dezoomify web page... but I got no answer... how can I find how the world digital library files its images.. i.e. If I want to download the bible from this page... http://www.wdl.org/en/item/9910/view/1/230/ can anybody give me any hint? Thanks :)

**Comment by lovasoa** [comment]
@Horemheb : as your question is not related to this thread, I opened a new issue : #5 .
