### ISSUE TITLE
National Library of Wales

### ISSUE THREAD

**Issue by emyrmorgan** [lovasoa/dezoomify#3]
Hi,

I've used your program in the past and I think that it is really great. I've tried to download an image from the National Library of Wales website but everything that I've tried before doesn't work. Am I being stupid or is there an issue with the file that is unsupported? The file is found here in Firebug console: value="zoomifyImagePath=delweddau/jws/jws00042.pff&zoomifyServerIP=www.llgc.org.uk&zoomifyServerPort=80&zoomifyTileHandlerPath=/zoomify/ZoomifyServlet&zoomifyInitialRotation=0"
Many thanks for your help, Emyr

**Comment by lovasoa** [comment]
Can you give a valid url to a page conatining a zoomify viewer ?

**Comment by emyrmorgan** [comment]
http://www.llgc.org.uk/drychdigidol/jws/JWS00001/37/zoom.html?lng=en

Thanks for your help, Emyr

**Comment by lovasoa** [comment]
Ok, the format used here seems a bit more complex than what is used normally in zoomify, and I didn't found any documentation about it, making it difficult to create a dezoomifier.

From what I understand:
Instead of using one file per tile, they use only one file that contains all the data.
That file is available on the server: http://www.llgc.org.uk/zoomify/delweddau/jws/jws00042.pff
But the viewer doesn't download it.

More exactly, it downloads parts of it, through API calls.
 - Seems to give the metadata: http://www.llgc.org.uk/zoomify/ZoomifyServlet?&requestType=1&file=delweddau%2Fjws%2Fjws00042.pff
 - Gives the indexes to use in the last API call: http://www.llgc.org.uk/zoomify/ZoomifyServlet?begin=17402&requestType=2&end=19450&file=delweddau%2Fjws%2Fjws00042%2Epff
 - Return a slice of the pff file, with a header at the beginning. If the parameters are correct, the slice forms a valid JPEG file: http://www.llgc.org.uk/zoomify/ZoomifyServlet?file=delweddau/jws/jws00042.pff&requestType=0&begin=1622936&end=1628538&vers=106&head=16342

**Comment by lovasoa** [comment]
I think I now mostly understand how the format works, and I started to document it here:
https://github.com/lovasoa/dezoomify/wiki/PFF-format-description

Implementing it in dezoomify might actually not be too hard.
I'll do it if I have time.

**Comment by lovasoa** [comment]
I finished documented the format. Everything needed to create a plugin is there, so if anyone is interested and has more time than me...

It must be a matter of hours.

**Comment by lovasoa** [comment]
Done !
It's in production here: http://ophir.alwaysdata.net/dezoomify/dezoomify.html

It's totally different from the traditionnal zoomify format, so I created a new plugin: "Zoomify PFF".

**Comment by emyrmorgan** [comment]
Awesome!

Sorry not to have replied sooner - only now I am sitting down after getting
chores done and children to bed.

I am in awe! I don't know how you worked all that out but I am really,
really impressed by your work.

Merci beaucoup, mon ami.

Is there anything that I can do for you in return?

Leave a review also?

Thanks a merci again,

Emyr

**Comment by lovasoa** [comment]
You are very welcome!
Thank you for opening this bug.
The only way you can thank me is by continuing to use this, and other open-source softwares.

I just wrote a small utility in C that converts PFF files to JPEG: [pff-extract](https://github.com/lovasoa/pff-extract). If you have many files, or large files to convert, you might want to use it instead of dezoomify, it is faster.

**Comment by emyrmorgan** [comment]
Thanks so much for your hard work in solving this problem. I probably won't
be able to use the utility, pff-extract, which you wrote as I don't have
the technical ability and have no real programming experience. However I
will be able to use the extractor, which is awesome, as is your skills!

Merci beaucoup,

Emyr Morgan.
