### ISSUE TITLE
[new site support] Van Gogh Museum

### ISSUE THREAD

**Issue by dancorpse** [lovasoa/dezoomify#309]
What's the zoom tool Van Gogh musesum use? It looks very similar to google art project, example here: 
https://www.vangoghmuseum.nl/nl/collectie/s0383V1987

The site provide downloading ,but not in full size. 

I find out the xhr file in browser's network inspector: 
https://vangoghmuseum-assetserver.appspot.com/tiles?id=5523511284072448, but dezoomify does not work with it.

**Comment by lovasoa** [comment]
Oh, it looks like they have their own format, that is not yet supported by dezoomify...

**Comment by lovasoa** [comment]
They seem to be using https://micr.io/. Micrio itself claims on their website that their latest version supports IIIF, which is supported by dezoomify. However, it looks like the version vangoghmuseum.nl uses is not based on IIIF.

**Comment by lovasoa** [comment]
I added support for this new format:

https://ophir.alwaysdata.net/dezoomify/dezoomify.html#https://www.vangoghmuseum.nl/nl/collectie/s0383V1987

![canvas](https://user-images.githubusercontent.com/552629/63116701-90664100-bf9a-11e9-8723-e4fb130fea6b.jpg)

**Comment by dancorpse** [comment]
That's great! You're a genius!

**Comment by MrChrisWin** [comment]
will this be supported on dezoomify? Thanks.

**Comment by lovasoa** [comment]
It is already supported in dezoomify. Did you mean dezoomify-rs ? You can open a feature request in dezoomify-rs.

**Comment by lovasoa** [comment]
Haha, looks like we are famous now 😆 

```
curl 'https://micr.io/i/WPTWb/0,0,1024,1024/1024,/0/default.png' -H 'Referer: dezoomify' 
Image scrapers are not allowed
```

When sending requests to micrio (who manages the vangoghmuseum.nl zoomable images) with a referrer that contains the string "dezoomify", they return a 403 error instead of the image. 

This is a little bit comical, because the `Referer` header is controlled by the client, so it's easy to work around.

Until I fix this in dezoomify itself, you can follow the [instructions for access-protected pages](https://github.com/lovasoa/dezoomify/wiki/How-to-access-protected-pages) on the wiki. Either open the browser console and paste `ZoomManager.proxy_tiles = "proxy.php";` before dezooming, or use [dezoomify-rs](https://dezoomify-rs.ophir.dev/) instead of dezoomify.


And to the developers and managers at micr.io who may be reading this : would you mind to have a chat ? It's a little bit ridiculous to play cat and mouse like that. You can send an email to contact at ophir dot dev, and I'll be happy to talk.

**Comment by lovasoa** [comment]
I updated dezoomify, it,doesn't send a referer anymore, everything should just work without any tweak from https://dezoomify.ophir.dev now.

**Comment by Joostb** [comment]
I just tried to download an image, but it appears that they changed something again. I get the following error: 
```
Error: Invalid JSON:
https://micrio.vangoghmuseum.nl/iiif/HDzja/info.json

(https://dezoomify.ophir.dev/dezoomify/zoommanager.js:217)
```

If i try to open the url, I get the following response: `403: Access Denied. Without hash, you are not allowed to use this api`.

On the website, they are calling to a similar looking url: `https://micrio-cdn.vangoghmuseum.nl/HDzja/info.json`.

Which does at least not return a 403

**Comment by lovasoa** [comment]
@Joostb : where did you get that URL from ? The manifest URL I see being used on the website is 

```
https://micrio-cdn.vangoghmuseum.nl/HDzja/info.json
```

which does work: 

https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://micrio-cdn.vangoghmuseum.nl/HDzja/info.json

**Comment by lovasoa** [comment]
Oh, I see. You are not using the dezoomify browser extension, but rather pasting the  viewer page from vangoghmuseum.nl directly into dezoomify, right ? You are using something like

https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.vangoghmuseum.nl/nl/collectie/s0383V1987

I'll fix that

**Comment by Joostb** [comment]
Sorry I wasn't clear. I didn't know  there was a browser extension. 
That was indeed what I tried.

Thanks for your quick reaction :+1:

**Comment by lovasoa** [comment]
It's fixed. https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.vangoghmuseum.nl/nl/collectie/s0383V1987 works now.

But I encourage you to use the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/) anyway. It's more flexible and less likely to break when websites change.
