### ISSUE TITLE
[feature request] handle invalid image paths gracefully in the zoomify dezoomer.

### ISSUE THREAD

**Issue by BaduguSridhar** [lovasoa/dezoomify#311]
we are unable to dezoomify this  http://hmdaprojects.hmda.gov.in/huda/Kukatpalli.aspx
howerver the same gets open when you launch direct link

can you please modify zoommanager.js to by pass such errors and dezoomify images.

Error details:
---------
Uncaught Error: Invalid XML:
http://hmdaprojects.hmda.gov.in/huda/Jinnaram/ImageProperties.xml

(https://ophir.alwaysdata.net/dezoomify/zoommanager.js:190)

**Comment by lovasoa** [comment]
Hello and thank you for taking the time of filling a bug report.

It looks like the page itself indicates a invalid image path: `<param name="FlashVars" value="zoomifyImagePath=Jinnaram"/>`

The page only works because it later indicates a second image path, that is valid: `FlashVars="zoomifyImagePath=Kukatpalli"`.

We could add support for switching to the next image path once the first is found to be invalid, but the architecture of dezoomify is not very well suited for that. If you want to submit a PR for that, you are welcome !

In the meantime, you can dezoom this image using the direct link to the meta-information file:
https://ophir.alwaysdata.net/dezoomify/dezoomify.html#http://hmdaprojects.hmda.gov.in/huda/Kukatpalli/ImageProperties.xml

**Comment by lovasoa** [comment]
![map](https://user-images.githubusercontent.com/552629/63337583-826d4300-c341-11e9-8efc-b9306900ded6.jpg)

**Comment by lovasoa** [comment]
Fixed by https://github.com/lovasoa/dezoomify/commit/006ed8f7a6e34cd92050aa58b9c0d9b827c72b89
