### ISSUE TITLE
[new site support]

### ISSUE THREAD

**Issue by Mahakam20000** [lovasoa/dezoomify#349]
### Site name and desciption
http://www.cflr.beniculturali.it/iip_viewer/iiifserver.php?dir=/AS_Roma/Imago/&file=Gregoriano/Mappe/Rieti/141.jp2
Italian online archive of public old map by cultural heritage.

Why is this site of particular interest ? The more popular the site, the more chance you have to see dezoomify supporting it someday.

I don't know if it is popular, but it is usefull for academic purposes.

### Example URLs
http://www.cflr.beniculturali.it/iip_viewer/iiifserver.php?dir=/AS_Roma/Imago/&file=Gregoriano/Mappe/Rieti/141.jp2

### Current error message
Describe the error dezoomify currently gives you when you try to dezoomify images from this site.

 Error
Uncaught Error: Unable to find a proper dezoomer for:
http://www.cflr.beniculturali.it/iip_viewer/iiifserver.php?dir=/AS_Roma/Imago/&file=Gregoriano/Mappe/Rieti/141.jp2

(https://ophir.alwaysdata.net/dezoomify/dezoomers/automatic.js:30)
You should read our Frequently Asked Questions, and, if you think this is an issue with dezoomify itself, report a bug on the bugtracker.

**Comment by Mahakam20000** [comment]
Problem solved using the URL of the vnd.netfpx file.
Sorry for my bad english and for the useless ticket.

**Comment by lovasoa** [comment]
Hello, no problem.
The URL to give to dezoomify is:

 http://www.cflr.beniculturali.it/iiifserver?FIF=/images/Patrimonio/Archivi//AS_Roma/Imago/Gregoriano/Mappe/Rieti/141.jp2&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number

I still haven't talked about it publicly because it still hasn't been approved on the Chrome Store, but I am developing a browser extension that finds the dezoomify URLs automatically. You can [help to beta-test it](https://github.com/lovasoa/dezoomify-extension/issues/1) if you want.
