### ISSUE TITLE
old browsers don't support String.prototype.endsWith

### ISSUE THREAD

**Issue by soft-for-people** [lovasoa/dezoomify#36]
Not worked for Zoomify (version 2?) at swaen.com:
http://www.swaen.com/zoomV2.php?id=28828&zif_first=true
for example.

Result:

Error !
TypeError: baseUrl.endsWith is not a function (http://ophir.alwaysdata.net/dezoomify/dezoomers/zoomify.js:15)

If you think this is an issue with dezoomify itself, you can report a bug on the bugtracker.

**Comment by lovasoa** [comment]
## The problem
There are two issues here:
 * You use an old browser that doesn't support `String.prototype.endsWith`.
 * The image is in the `.zif` format, that is not supported be dezoomify (see #21), but for which I created a [dedicated tool to dezoomify `ZIF` files](http://lovasoa.github.io/ZIF/).

## The solution
 * I'm going to use `.indexOf()` instead of `.endsWith()` in  the code.
 * I'm not going to add support for `zif`files in dezoomify for now. You can download the zif file of your example [here](http://www.swaen.com/os/zif/96098.zif) and dezoomify it using my ZIF file format implementation ([source code](https://github.com/lovasoa/ZIF/#), [use online](http://lovasoa.github.io/ZIF/)) or the one by @asherber ([source code](https://github.com/asherber/Zif.Reader))
