### ISSUE TITLE
Slovak National Gallery [new site support]

### ISSUE THREAD

**Issue by xmihalk** [lovasoa/dezoomify#378]
### Site name and desciption
It is the only one of kind [website]( https://www.webumenia.sk/en/) in Slovakia, where are uploaded many things  mainly from **Slovak National Gallery**, but there are lot of stuff from other Slovak culture institutions - 

> Web umenia is an online catalog of 133 532 artworks
of which 77 800 is in high resolution

### Example URLs

1. https://www.webumenia.sk/en/dielo/SVK:SNG.KD_391 
2. https://www.webumenia.sk/en/dielo/SVK:SNG.KD_391/zoom/

### Current error message
1. ```Uncaught Error: Invalid XML: https://www.webumenia.sk/en/dielo/SVK:SNG.KD_391/```
2. ```Uncaught Error: Unable to fetch https://www.webumenia.sk/en/dielo/SVK:SNG.KD_391/https:\/\/img.webumenia.sk\/zoom\/?path=%2FSNGBA%2FX400%2FSNG--KD_391--1_1--2015_05_21--L2_WEB.jp2.dzi```

**Comment by lovasoa** [comment]
Hello,
  The images from this website are already supported by dezoomify. In order to find the url to enter in the text field, you can use the [dezoomify browser extension](https://github.com/lovasoa/dezoomify-extension/#dezoomify-extension)


![canvas](https://user-images.githubusercontent.com/552629/79043683-f4f89f00-7c00-11ea-8668-f55eeef740c6.jpg)
