### ISSUE TITLE
imkinsky.com

### ISSUE THREAD

**Issue by Tricesimo** [lovasoa/dezoomify#407]
https://imkinsky.com/en/buying/list-of-prices-reached/131/7.681/83431-albin-egger-lienz

It appears that this site uses Zoomify, is there any way to get the image to download using Dezoomify?

**Comment by lovasoa** [comment]
Hello, 
  this is a zif image. You can find the URL of the image in your browser's inspector, then download it, and rename it to add the `.tif` extension. It should then open with your usual image viewer.

In this case, the URL is : 

https://imkinsky.com/objektimages/objekt/zoom/83431a.zif


![83431a-0](https://user-images.githubusercontent.com/552629/85204879-dce77f00-b317-11ea-91ac-6b000c126198.jpg)

**Comment by Tricesimo** [comment]
Thanks - I can find the zif file, and when I paste the link into my browser, it lets me download the file as a .zif. But, when I change the extension to .tif, I am not able to open it with anything - Photoshop, Windows Photo Viewer, web browser, even Paint. Is there something else that I need to do?

**Comment by lovasoa** [comment]
Hello,
  I cannot test any of the tools you mention since so not use windows. You can use the free and open-source image editor [the GIMP](https://www.gimp.org/), which opens the image without problems. You can also use [this small online ZIF opener](http://lovasoa.github.io/ZIF/) which I wrote a few years ago.
