### ISSUE TITLE
Add support for zoom.it

### ISSUE THREAD

**Issue by DThornz** [lovasoa/dezoomify#42]
I'm attempting to download this beautiful image displaying language and color I saw on this site:

http://fathom.info/colorful-language

Clearly you can see there's nothing there. So I went into the internet time machine and it works for some dates such as this:

https://web.archive.org/web/20150908100823/http://fathom.info/colorful-language

I've tried putting both sites into Dezoomify but it keeps returning:

Uncaught TypeError: Cannot read property 'documentElement' of null (http://ophir.alwaysdata.net/dezoomify/zoommanager.js:239)

This this a hopeless situation or is there a way to get that image?

**Comment by lovasoa** [comment]
The image is integrated into http://fathom.info/colorful-language, but your browser refuses to display it because of a [security policy](https://developer.mozilla.org/en-US/docs/Security/Mixed_content).

They use [zoom.it](http://zoom.it) for their zoomable images, which himself uses OpenSeadragon, but in an unconventional way. I'm going to add support for *zoom.it* and it'll work (even with the first URL where your browser doesn't display the image).

**Comment by lovasoa** [comment]
![languages](https://cloud.githubusercontent.com/assets/552629/15039329/42794f9c-12bd-11e6-805e-3a1d35201656.jpg)
