### ISSUE TITLE
britishmuseum

### ISSUE THREAD

**Issue by portraitsofrulers** [lovasoa/dezoomify#428]
Hello,
How to download high resolution images with dezoomify

https://www.britishmuseum.org/collection/object/PA_Painting-17
https://www.britishmuseum.org/collection/object/PA_Painting-21

**Comment by lovasoa** [comment]
Hello,
  The british museum uses the IIIF zoomable image format, which is already supported by dezoomify 🙂 You can simply install the [dezoomify browser extension](https://lovasoa.github.io/dezoomify-extension/), activate it and zoom on the picture. The extension will detect the zoomable image URL and open it in dezoomify.

**Comment by mahlerite57** [comment]
Hello,

Following on from issue #428
Haven't been successful with any British Museum images, eg:

https://www.britishmuseum.org/collection/object/P_1899-0729-1

Have tried the Web UI & the app.

Thanks for a fantastic app!

**Comment by lovasoa** [comment]
Hello! Can you be more specific? "It doesn't work" is not really the kind of bug report a developer expects. If you spend the time to write a detailed bug report, listing all the steps you've taken, what you expected, and what happened instead, then we may be able to pin down the issue.

**Comment by rhythmus** [comment]
D’abord et avant tout: Merci beaucoup d’avoir créé un outil aussi incroyable et précieux et de continuer à maintenir son développement si bien et loyalement. Vraiment magnifique!

Usually dezoomify is rock solid and is the only tool of its kind that supports so many deep-zoom protocols and resources. (AFAIK do [gigafineart](http://gigafineart.herokuapp.com/gcidownload) and [gapdecoder](https://github.com/gap-decoder/gapdecoder) only support G****e® Arts & Culture™ ؟)

Unfortunately, since May 2020, dezoomify has lost support for one of the most important collections of high-res art images on the Web: BritishMuseum.org.

If you could find some time and headspace to reopen this issue and investigate it, I’d be most happy with that. Merci beaucoup d’avance!

---
Using Firefox 77.0.1.

For all URLs below, dezoomify fails with these error messages:

> An error occured while trying to dezoomify your image. This is probably because dezoomify did not manage to find a zoomable image at the address you gave.
> Error: Unable to find a proper dezoomer for: [input URL]
> (https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)

This applies to almost all options (`Select automatically` | `Zoomify` | `IIPImage` | `Zoomify PFF` | `XLimage` | `TopViewer` | `krpano` | `IIIF` | `FSI` | `VLS` | `Micrio` | `Arts & Culture` | `Hungaricana`)

with the exception of `Generic dezoomer`, `Mnesys` and `Seadragon (Deep Zoom Image)` which trow either of these:

> Error: Unable to load tile.

> Error: Unable to find a mnesys viewer information file
> (https://dezoomify.ophir.dev/dezoomify/dezoomers/mnesys.js:34)

> Error: Invalid XML:
> [input URL]
> (https://dezoomify.ophir.dev/dezoomify/zoommanager.js:208)

Previously dezoomify may have been able to find the tile sources of zoomable images on pages from britishmuseum.org, but that capacity is currently lost. The dezoomify browser extension (Chrome) is no longer able to find the address of dezoomable images either.

**This is probably due to the major overhaul of the British Museum Collection website at the end of April 2020**:

- ‘Today we’re excited to launch a major revamp of our Collection online! 🏛 📲’ (2020-04-28) — https://twitter.com/britishmuseum/status/1255137718373249027

- ‘British Museum makes over half of its collection viewable online’ (2020-04-29) — https://www.engadget.com/british-museum-free-artifiact-images-023917176.html

- ‘The British Museum Has Put 300,000 Images of Its Most Famous Artworks Online So You Can Play Around With Them’ (2020-05-01) — https://news.artnet.com/art-world/british-museum-makes-collection-available-online-1850229

- ‘A new online collection launched in early 2020 includes new records and allows for new ways to search.’ (2020-05-22) — https://www.europeandataportal.eu/nl/news/british-museum-online-collection

_Note that the webpages of britishmuseum.org are not static HTML pages, but require a JavaScript runtime, and may produce invalid XML, which probably breaks dezoomify’s parser_?

- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_F-4-171
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_1848-0911-39
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_1848-0911-40
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_F-4-173
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_F-4-175
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_F-4-172
- https://dezoomify.ophir.dev/dezoomify/dezoomify.html#https://www.britishmuseum.org/collection/object/P_F-4-174

**Comment by lovasoa** [comment]
Hi @rhythmus, and thanks for the nice words. The british museum is still supported: they use the IIIF format, that is supported by dezoomify. To find the zoomable image URLs to give dezoomify, use [dezoomify-extension](https://lovasoa.github.io/dezoomify-extension/)

**Comment by rhythmus** [comment]
Hi @lovasoa, thanks for the quick follow-up! I had success, using:

- Firefox 77.0.1 (64-bits)
- Dezoomify Firefox addon, Version 0.4.3
- Mac OSX El Capitan (10.11.3)

However, on Chrome it seems to keep failing. I previously tried unsuccessfully always using the browser extension for Chrome. I now tried again in Chrome, but on a newer machine:

- Chrome Version 85.0.4183.83 (Official Build) (64-bit)
- Dezoomify Chrome extension, Version 0.4.3
- macOS Mojave Version 10.14.6

While the Dezoomify browser extension is listening and I am scrolling/zooming the OpenSeadragon viewer, and image tiles are being loaded and drawn onto a <canvas> in BritishMuseum.org webpages, the extension fails to find the TileSource URLs. Or perhaps it does, but anyway does not show the badge telling that it did. Also note that the extensions seems to consume lots of CPU on Chrome. My fans blow heavily and Chrome’s Task Manager shows a resource intensive process — until I deactivate the Dezoomify extension. Thought you might want to know.

Anyhow, I’m happy to be now able to use Dezoomify on BritishMuseum.org, at least on my old machine, using Firefox. Thanks, and keep up the good work!
