### ISSUE TITLE
canmore.org.uk

### ISSUE THREAD

**Issue by poyono** [lovasoa/dezoomify#481]
Hello everyone,

 I am having issues when trying to download https://canmore.org.uk/collection/932556

Dezoomify reports:

```
Uncaught Error: Unable to find a proper dezoomer for:
https://canmore.org.uk/collection/932556

(https://dezoomify.ophir.dev/dezoomify/dezoomers/automatic.js:30)
```
The image format doesn't seem to be like other Zoomify ones, the URLs are:
```https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0093/SC00932556.ptif/TileGroup0/**1-0-0**.jpg```

I tried to use generic dezoomer by doing:
```https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0093/SC00932556.ptif/TileGroup0/4-{{X}}-{{Y}}.jpg```
but this seemed to just create half a dozen versions of the tiles. 4 seems to be the highest zoom quality so that's where the 4 comes from, perhaps I'm just being stupid with the X and Y values. 

Anyone able to help?

**Comment by lovasoa** [comment]
Did you try the dezoomify extension to find the zoomable image url?

**Comment by lovasoa** [comment]
This website uses IIPSRV, whose native format is supported by dezoomify.

The URL to enter is : `http://zoom.rcahms.gov.uk/iipsrv?FIF=live/public/SC0093/SC00932556.ptif`

See: https://dezoomify.ophir.dev/dezoomify/dezoomify.html#http://zoom.rcahms.gov.uk/iipsrv?FIF=live/public/SC0093/SC00932556.ptif

Using the zoomify format as suggested by the extension doesnt work because the server forbids access to `https://zoom.rcahms.gov.uk/iipsrv?zoomify=live/public/SC0093/SC00932556.ptif/ImageProperties.xml`.
