### ISSUE TITLE
Dezoomify images on Masterfile.com?

### ISSUE THREAD

**Issue by FrankEBailey** [lovasoa/dezoomify#50]
Hi, thanks for all you hard work on this very useful tool. I have been using Firefox and a "save cached images" plugin to download individual tiles from zoomable images for years, and stitching them together in Photoshop to make wallpapers for my computer.  Dezoomify looks like it might be a massive time-saver, however I can't find the XML file in the network traffic as your FAQ recommends, and none of the other URLs I've tried in vain hope have worked either. It seems to use the SeaDragon PFF format but they look to have done some extra locking down because it's just not working :(

Would you mind taking a look and giving me an idea of whether it'd be possible to get Dezoomify working, for example on any image from the search at this URL? http://www.masterfile.com/em/search/#session=1464166286938&id=1464166286652&color=&colour_key=0&format=hvsp&imgtype=P&releases=&keyImage=&keyword=jungle+waterfall&license=RM&mode=search&sort=hatter

Thanks so much!

**Comment by lovasoa** [comment]
I just committed 4122bcd19d4711d9eec9ce47b29746a245c01c02, that allows you to put any tile URL, and dezoomify will find all the informations automatically. So you can inspect network traffic, lookink for *Images* instead of *XHR*, copy the URL of any of the tiles, and paste it to dezoomify.

If you want the all process to be faster, you can also download the pff file, and convert it to JPEG using another tool that I've written, [pff-extract](https://github.com/lovasoa/pff-extract).

**Comment by lovasoa** [comment]
![canvas](https://cloud.githubusercontent.com/assets/552629/15537719/0b9b83c4-2289-11e6-9bb6-8a5394e08fc3.jpg)
And this is one of the images you gave as an example.

**Comment by FrankEBailey** [comment]
Wow, this is fantastic! You're a life saver! :100:
