### ISSUE TITLE
Unable to find arts and culture image metadata URL

### ISSUE THREAD

**Issue by rofarias** [lovasoa/dezoomify#556]
Using Dezoomify Chrome extension to get the proper link

Link: https://artsandculture.google.com/asset/d-pedro-iv-no-leito-de-morte-abra%C3%A7a-o-soldado-manuel-pereira-de-ca%C3%A7adores-5/1QHg1_dHkhp4Ow?hl=pt-PT&ms=%7B%22x%22%3A0.5%2C%22y%22%3A0.5%2C%22z%22%3A8.704303446685817%2C%22size%22%3A%7B%22width%22%3A3.4051732653706357%2C%22height%22%3A1.2500000000000007%7D%7D

Link after clicking Chrome extension: https://artsandculture.google.com/asset/d-pedro-iv-no-leito-de-morte-abra%C3%A7a-o-soldado-manuel-pereira-de-ca%C3%A7adores-5/1QHg1_dHkhp4Ow?hl=pt-PT&ms=%7B%22x%22%3A0.5%2C%22y%22%3A0.5%2C%22z%22%3A8.718803016380932%2C%22size%22%3A%7B%22width%22%3A3.3711215327169293%2C%22height%22%3A1.2375000000000007%7D%7D

Error message below:

Uncaught Error: Unable to find arts and culture image metadata URL
(https://dezoomify.ophir.dev/dezoomify/dezoomers/arts-culture.js:7)

**Comment by lovasoa** [comment]
I cannot reproduce the issue. It works for me

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/552629/120539860-51f87b00-c3e8-11eb-9116-77ab3842c5fe.png">

**Comment by olaviinha** [comment]
I am facing this same issue, also with links provided above.

Removing line-break from `arts-culture.js` line 5 solved the issue for me:

**Before (did not work):**
``` 
let reg = /]\n,"(\/\/[^"/]+\/[^"/]+)",(?:"([^"]+)"|null)/m;
``` 

**After (works fine and dandy):**
```
let reg = /],"(\/\/[^"/]+\/[^"/]+)",(?:"([^"]+)"|null)/m;
```

**Comment by Colliwomple** [comment]
Can you explain me more detailed how to fix this!? Having the same issue  (Firefox and Safari) website just giving me the same errror

**Comment by olaviinha** [comment]
This is **not a fix** but a workaround you can perform on the spot if you have some kind of an idea how your browser developer tools work. Note that you need to do this every time you use the extension or otherwise enter the Dezoomify web page. Also I don't have Firefox or Safari at my disposal right now, but I suppose these Chrome instructions might come in handy:

1. Hit F12 to access developer tools.
2. Enter _Console_ tab.
3. Click on `at arts-culture.js:7` on the error message.
4. Remove `\n` from line 5.
5. Hit Cmd+S to save that js file you're editing.
6. Now click _Dezoomify !_ button on that page.

**Comment by lovasoa** [comment]
fixed :)
