### ISSUE TITLE
Uncaught Error: Unable to load tile.

### ISSUE THREAD

**Issue by AdvAnton** [lovasoa/dezoomify#637]
Hello

https://artsandculture.google.com/asset/light-of-the-world-william-holman-hunt/KgFluSyRk-NHkA

Guys please help me download this image, 2 days of fruitless actions, re-read the entire forum, nothing helps.

**Comment by JeovinL** [comment]
I noticed that too, you're using the .exe program right? Try using the web dezoomify extension, right now its still working

**Comment by lovasoa** [comment]
I cannot reproduce your issue. The download works fine in dezoomify: https://dezoomify.ophir.dev/#https://artsandculture.google.com/asset/light-of-the-world-william-holman-hunt/KgFluSyRk-NHkA

![r](https://user-images.githubusercontent.com/552629/180005453-651ad120-0d68-4d25-9045-a0119d23160e.jpg)


If your issue is not with the dezoomify web application, but with [the dezoomify-rs command-line program](https://dezoomify-rs.ophir.dev/) instead, you can open an issue on [the dedicated **dezoomify-rs** issue tracker](https://github.com/lovasoa/dezoomify-rs/issues) instead. (make sure you are using the latest version of the program before opening a new issue).

**Comment by lovasoa** [comment]
I tried the download with the latest dezoomify-rs (v2.9.1), and it works fine too. I uploaded the result to wikimedia commons: https://commons.wikimedia.org/wiki/File:Light_of_the_World_Hunt.jpg
