### ISSUE TITLE
help for collections.lib.uwm.edu

### ISSUE THREAD

**Issue by macdorli** [lovasoa/dezoomify#74]
I tried this but it does not work: http://collections.lib.uwm.edu/cdm/singleitem/collection/agseurope/id/1068
I also tried alternative methods .xml {{X}} {{Y}}
Can you help me? Thanks

**Comment by lovasoa** [comment]
You can download the image in full resolution directly.

![image](http://collections.lib.uwm.edu/utils/ajaxhelper/?CISOROOT=agseurope&CISOPTR=1068&action=2&DMSCALE=300&DMWIDTH=4660&DMHEIGHT=5120)

**Comment by macdorli** [comment]
Oooh cool, but how I get there?

**Comment by macdorli** [comment]
I saw the link, thank you :)

**Comment by lovasoa** [comment]
Just look at the network traffic while you zoom into the image. You'll see that image tiles have an URL that follows the pattern `http://collections.lib.uwm.edu/utils/ajaxhelper/?CISOROOT=agseurope&CISOPTR=1068&action=2&DMSCALE=200&DMWIDTH=512&DMHEIGHT=512&DMX=3584&DMY=3072&DMTEXT=&DMROTATE=0`.

The name of the different parameters in the URL are quite obvious, you just have to change them in order to get the full size image.

**Comment by macdorli** [comment]
Thanks 👍
