### ISSUE TITLE
Work on http://www.andreasgursky.com

### ISSUE THREAD

**Issue by apbonn** [lovasoa/dezoomify#86]
hi,

how is it possible to download pictures from this page?

http://www.andreasgursky.com/en/works/1993/paris-montparnasse

i always get an error.

Any ideas?

**Comment by lovasoa** [comment]
They use dezoomify. You just have to find where the meta-info file is. In your case: http://www.andreasgursky.com/tile.php?f=3-works/0-1993/10-paris-montparnasse/zoom/ImageProperties.xml

Just give that to dezoomify, it'll work.

**Comment by lovasoa** [comment]
![immeuble](https://cloud.githubusercontent.com/assets/552629/18711670/10068634-801c-11e6-97fe-c81d53ead391.jpg)

**Comment by LasseMacchiato** [comment]
This method doesn't seem to work anymore. Instead of the actual XML file, a dummy `<img>` tag is returned:

`<img src="https://www.andreasgursky.com/tile.php?f=3-works/0-1993/10-paris-montparnasse/zoom/ImageProperties.xml" alt="Die Grafik &quot;https://www.andreasgursky.com/tile.php?f=3-works/0-1993/10-paris-montparnasse/zoom/ImageProperties.xml&quot; kann nicht angezeigt werden, weil sie Fehler enthält.">`

The link provided you provided doesn't work either.
