### ISSUE TITLE
Add Support for Gallica

### ISSUE THREAD

**Issue by Horemheb** [lovasoa/dezoomify#9]
Hello. I got problems dezoomifiying pages from Gallica..
for example this manuscript is currently not dezoomifyable..
http://gallica.bnf.fr/ark:/12148/btv1b8449691v/f11.item
Could you please add support, as you always so kindly do?
Thanks!

**Comment by lovasoa** [comment]
The good new is that for [Gallica](http://gallicalabs.bnf.fr),you don't need a tool such as zoomify, because you can download the full size images directly from their website.

The new version of the Gallica viewer uses [IIIF](http://iiif.io/), which is a full featured zoomable image format which offers the client the ability to access full size images.

All you have to do is find the **identifier** of the image you want to download. It is in the url of the page, it starts with `ark:` and ends with `f{n}`, where `{n}` is the page number in the book.
In your example (http://gallica.bnf.fr/ark:/12148/btv1b8449691v/f11.item), the **identifier** is `ark:/12148/btv1b8449691v/f11`.

The you can access your image at the following url : `http://gallicalabs.bnf.fr/iiif/{identifier}/full/full/0/native.png`, where you replace `{identifier}` with the identifier you just extracted.

In your example, it gives:  http://gallicalabs.bnf.fr/iiif/ark:/12148/btv1b8449691v/f11/full/full/0/native.png
